name: create_delete_cluster

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

    paths:
      - "apply/**"
      - "delete/**"

jobs:
  create_delete_cluster:
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v2
      # Install kubectl and vsphere plugin
      - name: Install cli tools
        run: |
          sudo mv kubectl* /usr/bin/
          sudo chmod +x /usr/bin/kubectl*
      # Install and login to Tailscale network
      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      # Login to TKG env
      - name: login
        env:
          KUBECTL_VSPHERE_PASSWORD: ${{ secrets.KUBECTL_VSPHERE_PASSWORD }}
        run: |
          kubectl vsphere login --server=${{ secrets.IPADRESS }} --insecure-skip-tls-verify -u=${{ secrets.KUBECTL_VSPHERE_USER }}
          kubectl config use-context ${{ secrets.KUBECTL_CONTEXT }}
      # Apply the yaml files
      - name: apply
        continue-on-error: true
        run: kubectl apply -f apply/.
      # Delete the yaml files
      - name: delete
        continue-on-error: true
        run: kubectl delete -f delete/. --wait=false
      # Logout of Tailscale network and remove agent
      - name: Delete Tailscale agent
        run: sudo tailscale logout
