name: apply_cluster

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

    paths:
      - "apply/**"

jobs:
  apply_cluster:
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cli tools
        run: |
          sudo mv kubectl* /usr/bin/
          sudo chmod +x /usr/bin/kubectl*
      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: login
        env:
          KUBECTL_VSPHERE_PASSWORD: ${{ secrets.KUBECTL_VSPHERE_PASSWORD }}
        run: |
          kubectl vsphere login --server=172.19.24.1 --insecure-skip-tls-verify -u=${{ secrets.KUBECTL_VSPHERE_USER }}
          kubectl config use-context ${{ secrets.KUBECTL_CONTEXT }}
          kubectl apply -f apply/.
      - name: Delete Tailscale agent
        run: sudo tailscale logout
