name: deploy_cluster

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  deploy_cluster:
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cli tools
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mkdir -p ~/.local/bin
          mv ./kubectl ~/.local/bin/kubectl
          unzip plugins/vsphere-plugin.zip -d ~/.local/bin
      - name: test
        run: kubectl --help
      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Delete Tailscale agent
        run: sudo tailscale logout
